INSERT INTO `cilos` (`course_code`, `index`, `content`, `avg_score`) VALUES ('CS001', 1, 'math', NULL);
INSERT INTO `cilos` (`course_code`, `index`, `content`, `avg_score`) VALUES ('CS001', 2, 'logic', NULL);
INSERT INTO `cilos` (`course_code`, `index`, `content`, `avg_score`) VALUES ('CS002', 1, 'understanding', NULL);
INSERT INTO `cilos` (`course_code`, `index`, `content`, `avg_score`) VALUES ('CS002', 2, 'application', NULL);
INSERT INTO `cilos` (`course_code`, `index`, `content`, `avg_score`) VALUES ('CS003', 1, 'understanding', NULL);
INSERT INTO `cilos` (`course_code`, `index`, `content`, `avg_score`) VALUES ('CS003', 2, 'application', NULL);
INSERT INTO `cilos` (`course_code`, `index`, `content`, `avg_score`) VALUES ('CS102', 1, 'c programming', NULL);
INSERT INTO `cilos` (`course_code`, `index`, `content`, `avg_score`) VALUES ('CS102', 2, 'html', NULL);
INSERT INTO `cilos` (`course_code`, `index`, `content`, `avg_score`) VALUES ('CS102', 3, 'css', NULL);
INSERT INTO `cilos` (`course_code`, `index`, `content`, `avg_score`) VALUES ('CS103', 1, 'programming', NULL);
INSERT INTO `cilos` (`course_code`, `index`, `content`, `avg_score`) VALUES ('CS103', 2, 'html', NULL);
INSERT INTO `cilos` (`course_code`, `index`, `content`, `avg_score`) VALUES ('CS103', 3, 'python', NULL);
INSERT INTO `cilos` (`course_code`, `index`, `content`, `avg_score`) VALUES ('CS104', 1, 'document writing', NULL);
INSERT INTO `cilos` (`course_code`, `index`, `content`, `avg_score`) VALUES ('CS104', 2, 'programming', NULL);
INSERT INTO `cilos` (`course_code`, `index`, `content`, `avg_score`) VALUES ('CS104', 3, 'database', NULL);
INSERT INTO `cilos` (`course_code`, `index`, `content`, `avg_score`) VALUES ('CS201', 1, 'basic info', NULL);
INSERT INTO `cilos` (`course_code`, `index`, `content`, `avg_score`) VALUES ('CS201', 2, 'logic', NULL);
INSERT INTO `cilos` (`course_code`, `index`, `content`, `avg_score`) VALUES ('CS201', 3, 'programming', NULL);
INSERT INTO `cilos` (`course_code`, `index`, `content`, `avg_score`) VALUES ('ENG001', 1, 'Write', NULL);
INSERT INTO `cilos` (`course_code`, `index`, `content`, `avg_score`) VALUES ('ENG001', 2, 'Speak', NULL);
INSERT INTO `cilos` (`course_code`, `index`, `content`, `avg_score`) VALUES ('ENG001', 3, 'Listen', NULL);
INSERT INTO `cilos` (`course_code`, `index`, `content`, `avg_score`) VALUES ('ENG002', 1, 'Write', NULL);
INSERT INTO `cilos` (`course_code`, `index`, `content`, `avg_score`) VALUES ('ENG002', 2, 'Speak', NULL);
INSERT INTO `cilos` (`course_code`, `index`, `content`, `avg_score`) VALUES ('ENG002', 3, 'Listen', NULL);
INSERT INTO `cilos` (`course_code`, `index`, `content`, `avg_score`) VALUES ('ENG003', 1, 'Write', NULL);
INSERT INTO `cilos` (`course_code`, `index`, `content`, `avg_score`) VALUES ('ENG003', 2, 'Listen', NULL);
INSERT INTO `cilos` (`course_code`, `index`, `content`, `avg_score`) VALUES ('ENG003', 3, 'Speak', NULL);
INSERT INTO `cilos` (`course_code`, `index`, `content`, `avg_score`) VALUES ('FE001', 1, 'introduction to physics', NULL);
INSERT INTO `cilos` (`course_code`, `index`, `content`, `avg_score`) VALUES ('FE001', 2, 'understanding', NULL);
INSERT INTO `cilos` (`course_code`, `index`, `content`, `avg_score`) VALUES ('FE002', 1, 'basic info', NULL);
INSERT INTO `cilos` (`course_code`, `index`, `content`, `avg_score`) VALUES ('FE002', 2, 'prepare income statement', NULL);
