INSERT INTO `courses` (`course_code`, `course_name`, `course_type`, `department`, `unit`, `year`) VALUES ('CS001', 'Discrete Structure', 'MR', 'CST', 3, '2011');
INSERT INTO `courses` (`course_code`, `course_name`, `course_type`, `department`, `unit`, `year`) VALUES ('CS002', 'Structure Programming', 'MR', 'CST', 3, '2012');
INSERT INTO `courses` (`course_code`, `course_name`, `course_type`, `department`, `unit`, `year`) VALUES ('CS003', 'Java', 'MR', 'CST', 3, '2012');
INSERT INTO `courses` (`course_code`, `course_name`, `course_type`, `department`, `unit`, `year`) VALUES ('CS102', 'Workshop I', 'MR', 'CST', 1, '2010');
INSERT INTO `courses` (`course_code`, `course_name`, `course_type`, `department`, `unit`, `year`) VALUES ('CS103', 'Workshop II', 'MR', 'CST', 1, '2012');
INSERT INTO `courses` (`course_code`, `course_name`, `course_type`, `department`, `unit`, `year`) VALUES ('CS104', 'Workshop III', 'MR', 'CST', 1, '2013');
INSERT INTO `courses` (`course_code`, `course_name`, `course_type`, `department`, `unit`, `year`) VALUES ('CS201', 'Database', 'MR', 'CST', 3, '2012');
INSERT INTO `courses` (`course_code`, `course_name`, `course_type`, `department`, `unit`, `year`) VALUES ('ENG001', 'English I', 'MR', 'CST', 3, '2011');
INSERT INTO `courses` (`course_code`, `course_name`, `course_type`, `department`, `unit`, `year`) VALUES ('ENG002', 'English II', 'MR', 'CST', 3, '2012');
INSERT INTO `courses` (`course_code`, `course_name`, `course_type`, `department`, `unit`, `year`) VALUES ('ENG003', 'English III', 'MR', 'CST', 3, '2012');
INSERT INTO `courses` (`course_code`, `course_name`, `course_type`, `department`, `unit`, `year`) VALUES ('FE001', 'Physics', 'FE', 'FM', 3, '2011');
INSERT INTO `courses` (`course_code`, `course_name`, `course_type`, `department`, `unit`, `year`) VALUES ('FE002', 'Accounting', 'FE', 'ACCT', 3, '2012');
