"""add type field to pre

Revision ID: a22fc74f107c
Revises: 02f640d25b89
Create Date: 2021-05-17 16:16:32.631712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a22fc74f107c'
down_revision = '02f640d25b89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pre', sa.Column('type', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pre', 'type')
    # ### end Alembic commands ###
