"""update

Revision ID: a799d2a81167
Revises: e45c7add2e9f
Create Date: 2021-04-29 20:49:15.729327

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a799d2a81167'
down_revision = 'e45c7add2e9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lecturers', sa.Column('gender', sa.String(length=10), nullable=True))
    op.add_column('lecturers', sa.Column('staffHonor', sa.String(length=20), nullable=True))
    op.alter_column('lecturers', 'program',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.add_column('students', sa.Column('gender', sa.String(length=10), nullable=True))
    op.alter_column('students', 'program',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'program',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.drop_column('students', 'gender')
    op.alter_column('lecturers', 'program',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.drop_column('lecturers', 'staffHonor')
    op.drop_column('lecturers', 'gender')
    # ### end Alembic commands ###
