"""empty message

Revision ID: e2a558a5ad9c
Revises: a799d2a81167
Create Date: 2021-05-11 00:45:45.490957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2a558a5ad9c'
down_revision = 'a799d2a81167'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pre', sa.Column('type', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pre', 'type')
    # ### end Alembic commands ###
