"""update

Revision ID: e45c7add2e9f
Revises: 
Create Date: 2021-04-29 20:38:38.597821

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e45c7add2e9f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('role', mysql.VARCHAR(length=30), nullable=True))
    # ### end Alembic commands ###
